services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supa-user
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s